"""Generate docs/RULES.md from sentinel.render.TITLE + core weights.

Usage:
    python docs/build_rules_table.py          # updates docs/RULES.md
    python docs/build_rules_table.py --check  # exits 0 if current, 1 if drift
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from sentinel.render import TITLE  # noqa: E402

# (weight, classification)
# classification: decisive | ceiling | observation | penalty
CORE_METADATA: dict[str, tuple[int, str]] = {
    "S1a": (50, "decisive"),
    "S1b": (15, "penalty"),
    "S2": (35, "penalty"),
    "S4": (25, "penalty"),
    "S5": (40, "penalty"),
    "S6": (15, "penalty"),
    "S7": (45, "decisive"),
    "S10": (70, "decisive"),
    "S11": (40, "ceiling"),
    "S12": (35, "penalty"),
    "S13": (45, "decisive"),
    "S14b": (25, "ceiling"),
    "S16": (0, "observation / ceiling"),
    "S17a": (25, "ceiling"),
    "S17b": (70, "decisive"),
    "S18a": (60, "decisive"),
    "S18b": (30, "penalty"),
    "S18c": (60, "decisive"),
    "S19": (25, "ceiling"),
    "S20": (30, "ceiling"),
    "S21": (40, "penalty / observation"),
    "S22": (30, "penalty / observation"),
    "S23": (30, "penalty / observation"),
    "S24": (35, "penalty / observation"),
    "S25": (30, "penalty"),
    "S26": (30, "penalty"),
    "D1": (40, "ceiling"),
    "D2": (0, "observation"),
}


def rule_sort_key(rid: str) -> tuple:
    m = re.match(r"([A-Z]+)(\d+)([a-z]*)", rid)
    if m:
        prefix, num, suffix = m.groups()
        return (0 if prefix == "S" else 1, int(num), suffix)
    return (2, rid)


def generate_markdown() -> str:
    missing = set(TITLE.keys()) ^ set(CORE_METADATA.keys())
    if missing:
        raise ValueError(f"Drift between render.TITLE and CORE_METADATA: {missing}")

    lines = [
        "# Sentinel Rule Reference",
        "",
        "This table is generated by [`docs/build_rules_table.py`](build_rules_table.py) from `sentinel.render.TITLE` and engine rule definitions.",
        "A test asserts that this document is current and never drifts.",
        "",
        "### Classifications",
        "- **decisive**: Deterministic evidence of malicious intent or dangerous behaviour. Forces verdict `COMPROMISED` regardless of arithmetic.",
        "- **ceiling**: Architectural risk or unapproved hook/server. Verdict cannot be `CLEAN` until approved by a human (score capped at 79).",
        "- **observation**: Shown to the user for awareness, but has penalty 0 and does not change the score or verdict.",
        "- **penalty**: Standard arithmetic deduction. Multiple penalties accumulate toward `SUSPICIOUS` or `COMPROMISED`.",
        "",
        "| Rule ID | Meaning | Weight | Classification |",
        "|---|---|:---:|---|",
    ]

    for rid in sorted(TITLE.keys(), key=rule_sort_key):
        meaning = TITLE[rid].title()
        meaning = re.sub(r"\bMcp\b", "MCP", meaning)
        meaning = re.sub(r"\bApi\b", "API", meaning)
        meaning = re.sub(r"\bUrl\b", "URL", meaning)
        meaning = re.sub(r"\bSsh\b", "SSH", meaning)
        weight, kind = CORE_METADATA[rid]
        weight_str = f"−{weight}" if weight > 0 else "0"
        lines.append(f"| **{rid}** | {meaning} | {weight_str} | {kind} |")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    target = ROOT / "docs" / "RULES.md"
    content = generate_markdown()
    if "--check" in sys.argv:
        if not target.exists():
            print(f"FAIL: {target} does not exist. Run python docs/build_rules_table.py")
            return 1
        current = target.read_text(encoding="utf-8")
        if current != content:
            print(f"FAIL: {target} is not current. Run python docs/build_rules_table.py")
            return 1
        print("OK: docs/RULES.md is up to date.")
        return 0

    target.write_text(content, encoding="utf-8")
    print(f"Wrote {len(TITLE)} rules to {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
